services:
  - type: web
    name: ajuaaa
    env: static
    buildCommand: cd comicss && npm ci && npm run build -- --base-href=/
    staticPublishPath: comicss/dist/comicss
    routes:
      - type: rewrite
        source: /*
        destination: /index.html